# -*- coding: utf-8 -*-
"""Set matrix zeros

Automatically generated by Colaboratory.



#Given a matrix if an element in the matrix is 0 then you will have to set its entire column and row to 0 and then return the matrix.

def setZeroes(mat):
  matrix = mat
  row = len(matrix)
  col = len(matrix[0])
  c = []; d = [];
  for i in range(row):
    for j in range(col):
      if matrix[i][j] == 0:
        c.append(i)
        d.append(j)

  a = matrix
  n = len(c)
  for p in range(n):
    for i in range(row):
      for j in range(col):
        if c[p] == i or d[p] == j:
          a[i][j] = 0

  return a

mat = [[1,1,1],[1,0,1],[1,1,1]]
setZeroes(mat)
